# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.CharField(choices=[('BLE', 'Bleach'), ('DBZ', 'Dragonballz'), ('SAO', 'Sword Art Online')], default='', max_length=3),
        ),
    ]
