# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200317_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.CharField(choices=[('Bleach', 'Bleach'), ('DragonballZ', 'Dragonballz'), ('Sword Art Online', 'Sword Art Online')], default='', max_length=16),
        ),
    ]
