# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200318_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=270),
        ),
    ]
